[project]
name = "my-project"
version = "0.1.0"
description = "A simple Fibonacci number calculator"
authors = ["Your Name <you@example.com>"]
license = "MIT"
dependencies = []

[build-system]
requires = ["uv"]
build-backend = "uv.build"
