[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my-project"
version = "0.1.0"
py_modules = ["fib"]

[tool.setuptools]
find:
  include:
    - fib.py
  exclude:
    - test_fib.py
